name: TodoApp
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: ja

settings:
  base:
    SWIFT_VERSION: 5.0
    OTHER_SWIFT_FLAGS: -D DEVELOP -Xfrontend -warn-long-expression-type-checking=200 -Xfrontend -warn-long-function-bodies=200

packages:    
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    exactVersion: 5.1.0
  RxGRDB:
    url: https://github.com/RxSwiftCommunity/RxGRDB.git
    exactVersion: 1.0.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift.git
    exactVersion: 5.1.1
  RxRelay:
    url: https://github.com/ReactiveX/RxSwift.git
    exactVersion: 5.1.1

targets:
  TodoApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.sample.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"TodoApp/Resources/Preview Content\""
        DEVELOPMENT_LANGUAGE: jp
    sources:
      - path: TodoApp
        excludes:
          - "**/.gitignore"
      - path: TodoApp/DI/NeedleGenerated.swift
        optional: true
        createIntermediateGroups: true
      - path: TodoApp/DI/NeedleGenerated.swift
        optional: true
        createIntermediateGroups: true
      - path: TodoApp/Resources/Generated/Strings+Generated.swift
        optional: true
        createIntermediateGroups: true
      - path: TodoApp/Resources/Generated/XCAssets+Generated.swift
        optional: true
        createIntermediateGroups: true        
    dependencies:
      - target: Core    
      - carthage: NeedleFoundation
    preBuildScripts:      
      - name: Run needle
        path: /bin/sh
        outputFiles:
          - $SRCROOT/TodoApp/DI/NeedleGenerated.swift
        script:  ./scripts/needle.sh
      - name: Run SwiftGen
        path: /bin/sh
        outputFiles:
          - $SRCROOT/TodoApp/Resources/Generated/Strings+Generated.swift
          - $SRCROOT/TodoApp/Resources/Generated/XCAssets+Generated.swift
        script: ./scripts/swiftgen.sh
    postCompileScripts:
      - name: Run SwiftFormat
        path: /bin/sh
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        path: /bin/sh
        script: ./scripts/swiftlint.sh

  Core:
    type: framework
    platform: iOS    
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.sample.${PRODUCT_NAME}
    sources:
      - Core
    dependencies:
      - carthage: NeedleFoundation
      - package: RxSwift
      - package: RxRelay
      - package: GRDB
      - package: RxGRDB
    postCompileScripts:
      - name: Run SwiftFormat
        path: /bin/sh
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        path: /bin/sh
        script: ./scripts/swiftlint.sh      

schemes:
  TodoApp:
    build:
      targets:
        TodoApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Release
  Core:
    build:
      targets:
        Core: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Release    
